version: '3'

services:
  cnd-postgres:
    container_name: cnd-postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=condominio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "15432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - postgres-network
      
  cnd-pgadmin:
    container_name: cnd-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=gabrielmarques.mg@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "15532:80"
    depends_on:
      - cnd-postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge

volumes:
  postgresql:
  postgresql_data: